let salonsData = [
	{
		info: {
			id: 1,
			title: 'Twiyo',
			address: '410 Chinook Avenue',
			contact_phone: '+81 545 614 0901',
			status: 'open',
			work_schedule: 'ПН-СБ',
			time_begin: '8:00',
			time_end: '18:00',
			type: 'SALON',
			images: [
				'http://dummyimage.com/148x100.png/5fa2dd/ffffff',
				'http://dummyimage.com/163x100.png/dddddd/000000',
				'http://dummyimage.com/149x100.png/ff4444/ffffff',
				'http://dummyimage.com/178x100.png/dddddd/000000',
			],
		},
		masters: [
			{
				id: 1,
				gender: 'F',
				name: 'George',
				work_schedule: 'ПН-СБ',
				telegram_id: 'g0',
				surname: 'Franceschelli',
				image: 'https://robohash.org/optiodistinctiopariatur.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 2,
				gender: 'M',
				name: 'Mischa',
				work_schedule: 'ПН-СБ',
				telegram_id: 'm1',
				surname: 'Blues',
				image: 'https://robohash.org/delectusillumet.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 3,
				gender: 'F',
				name: 'Thomasin',
				work_schedule: 'ПН-СБ',
				telegram_id: 't2',
				surname: 'Meigh',
				image: 'https://robohash.org/optioeafacilis.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 4,
				gender: 'M',
				name: 'Ruprecht',
				work_schedule: 'ПН-СБ',
				telegram_id: 'r3',
				surname: 'Chisman',
				image: 'https://robohash.org/molestiascorruptivoluptas.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 5,
				gender: 'M',
				name: 'Cristobal',
				work_schedule: 'ПН-СБ',
				telegram_id: 'c4',
				surname: 'Pactat',
				image: 'https://robohash.org/ipsavoluptatemea.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
		],
		services: [
			{
				title: 'Human Resources Manager',
				description: 'Other fracture of upper end of right ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing',
				price: 1500,
				min_time: 69,
			},
			{
				title: 'Help Desk Technician',
				description: 'Right lower quadrant abdominal tenderness',
				price: 1500,
				min_time: 40,
			},
			{
				title: 'Marketing Assistant',
				description: 'Toxic effect of petroleum products, assault, sequela',
				price: 1500,
				min_time: 65,
			},
			{
				title: 'Assistant Professor',
				description: 'Displaced fracture of neck of fourth metacarpal bone, right hand, subsequent encounter for fracture with malunion',
				price: 1500,
				min_time: 47,
			},
			{
				title: 'Account Executive',
				description: 'Fistula, other specified site',
				price: 1500,
				min_time: 3,
			},
		],
	},
	{
		info: {
			id: 2,
			title: 'Realcube',
			address: '042 Gale Circle',
			contact_phone: '+63 386 231 9694',
			status: 'open',
			work_schedule: 'ПН-СБ',
			time_begin: '8:00',
			time_end: '18:00',
			type: 'SALON',
			images: [
				'http://dummyimage.com/237x100.png/dddddd/000000',
				'http://dummyimage.com/181x100.png/ff4444/ffffff',
				'http://dummyimage.com/192x100.png/dddddd/000000',
				'http://dummyimage.com/165x100.png/ff4444/ffffff',
				'http://dummyimage.com/141x100.png/cc0000/ffffff',
				'http://dummyimage.com/247x100.png/dddddd/000000',
			],
		},
		masters: [
			{
				id: 1,
				gender: 'M',
				name: 'Drake',
				work_schedule: 'ПН-СБ',
				telegram_id: 'd0',
				surname: 'Ritzman',
				image: 'https://robohash.org/estveldelectus.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 2,
				gender: 'F',
				name: 'Georgetta',
				work_schedule: 'ПН-СБ',
				telegram_id: 'g1',
				surname: 'Bolland',
				image: 'https://robohash.org/repellendusquiaccusamus.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 3,
				gender: 'F',
				name: 'Debor',
				work_schedule: 'ПН-СБ',
				telegram_id: 'd2',
				surname: 'Dudbridge',
				image: 'https://robohash.org/voluptatemmolestiaesint.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 4,
				gender: 'M',
				name: 'Rob',
				work_schedule: 'ПН-СБ',
				telegram_id: 'r3',
				surname: 'Macak',
				image: 'https://robohash.org/voluptatemomnisexplicabo.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 5,
				gender: 'F',
				name: 'Ambur',
				work_schedule: 'ПН-СБ',
				telegram_id: 'a4',
				surname: 'Tilson',
				image: 'https://robohash.org/aharumvoluptatem.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
		],
		services: [
			{
				title: 'Human Resources Manager',
				description: 'Adverse effect of unspecified hormones and synthetic substitutes',
				price: 1500,
				min_time: 33,
			},
			{
				title: 'Chief Design Engineer',
				description: 'Brown-Sequard syndrome at C8 level of cervical spinal cord',
				price: 1500,
				min_time: 100,
			},
			{
				title: 'Research Associate',
				description: 'Late syphilis, unspecified',
				price: 1500,
				min_time: 20,
			},
			{
				title: 'VP Sales',
				description: 'Other superficial bite of other specified part of neck, subsequent encounter',
				price: 1500,
				min_time: 45,
			},
			{
				title: 'Help Desk Technician',
				description: 'Other osteoporosis with current pathological fracture, unspecified shoulder',
				price: 1500,
				min_time: 97,
			},
		],
	},
	{
		info: {
			id: 3,
			title: 'Jayo',
			address: '7 Heffernan Hill',
			contact_phone: '+55 320 321 9843',
			status: 'open',
			work_schedule: 'ПН-СБ',
			time_begin: '8:00',
			time_end: '18:00',
			type: 'SALON',
			images: [
				'http://dummyimage.com/125x100.png/dddddd/000000',
				'http://dummyimage.com/221x100.png/cc0000/ffffff',
				'http://dummyimage.com/136x100.png/5fa2dd/ffffff',
				'http://dummyimage.com/140x100.png/5fa2dd/ffffff',
				'http://dummyimage.com/249x100.png/dddddd/000000',
				'http://dummyimage.com/250x100.png/ff4444/ffffff',
				'http://dummyimage.com/167x100.png/ff4444/ffffff',
				'http://dummyimage.com/111x100.png/cc0000/ffffff',
				'http://dummyimage.com/233x100.png/ff4444/ffffff',
				'http://dummyimage.com/104x100.png/cc0000/ffffff',
			],
		},
		masters: [
			{
				id: 1,
				gender: 'F',
				name: 'Tonia',
				work_schedule: 'ПН-СБ',
				telegram_id: 't0',
				surname: 'Wortt',
				image: 'https://robohash.org/aspernaturpraesentiumnemo.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 2,
				gender: 'M',
				name: 'Clemens',
				work_schedule: 'ПН-СБ',
				telegram_id: 'c1',
				surname: 'Cornill',
				image: 'https://robohash.org/quaeoptiorepellendus.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 3,
				gender: 'M',
				name: 'Willis',
				work_schedule: 'ПН-СБ',
				telegram_id: 'w2',
				surname: 'Keller',
				image: 'https://robohash.org/etpariaturvoluptates.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 4,
				gender: 'M',
				name: 'Odo',
				work_schedule: 'ПН-СБ',
				telegram_id: 'o3',
				surname: 'Bracken',
				image: 'https://robohash.org/recusandaequosiure.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 5,
				gender: 'M',
				name: 'Oliver',
				work_schedule: 'ПН-СБ',
				telegram_id: 'o4',
				surname: 'Spybey',
				image: 'https://robohash.org/saepedoloresquis.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
		],
		services: [
			{
				title: 'Director of Sales',
				description: 'Nondisplaced fracture of pisiform, unspecified wrist, subsequent encounter for fracture with routine healing',
				price: 1500,
				min_time: 84,
			},
			{
				title: 'Professor',
				description: 'Other specified injury of dorsal artery of right foot, initial encounter',
				price: 1500,
				min_time: 22,
			},
			{
				title: 'Administrative Officer',
				description: 'Calculus of bile duct without cholangitis or cholecystitis with obstruction',
				price: 1500,
				min_time: 83,
			},
			{
				title: 'Nurse Practicioner',
				description: 'Poisoning by unspecified general anesthetics, undetermined, sequela',
				price: 1500,
				min_time: 44,
			},
			{
				title: 'Design Engineer',
				description: 'Poisoning by antimycobacterial drugs, intentional self-harm, subsequent encounter',
				price: 1500,
				min_time: 62,
			},
		],
	},
	{
		info: {
			id: 4,
			title: 'Linkbuzz',
			address: '44324 Menomonie Trail',
			contact_phone: '+507 595 920 2958',
			status: 'open',
			work_schedule: 'ПН-СБ',
			time_begin: '8:00',
			time_end: '18:00',
			type: 'SALON',
			images: [
				'http://dummyimage.com/205x100.png/ff4444/ffffff',
				'http://dummyimage.com/205x100.png/cc0000/ffffff',
				'http://dummyimage.com/114x100.png/5fa2dd/ffffff',
				'http://dummyimage.com/242x100.png/ff4444/ffffff',
				'http://dummyimage.com/219x100.png/5fa2dd/ffffff',
				'http://dummyimage.com/103x100.png/5fa2dd/ffffff',
			],
		},
		masters: [
			{
				id: 1,
				gender: 'F',
				name: 'Eartha',
				work_schedule: 'ПН-СБ',
				telegram_id: 'e0',
				surname: 'Seebert',
				image: 'https://robohash.org/atquevoluptatumaspernatur.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 2,
				gender: 'F',
				name: 'Cayla',
				work_schedule: 'ПН-СБ',
				telegram_id: 'c1',
				surname: 'Scorton',
				image: 'https://robohash.org/fugiatvoluptasvoluptatem.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 3,
				gender: 'F',
				name: 'Kristal',
				work_schedule: 'ПН-СБ',
				telegram_id: 'k2',
				surname: 'Silvermann',
				image: 'https://robohash.org/rerumsapienterepudiandae.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 4,
				gender: 'F',
				name: 'Allyson',
				work_schedule: 'ПН-СБ',
				telegram_id: 'a3',
				surname: 'Della Scala',
				image: 'https://robohash.org/laborumdolorcorrupti.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 5,
				gender: 'M',
				name: 'Alfonso',
				work_schedule: 'ПН-СБ',
				telegram_id: 'a4',
				surname: 'Fiddian',
				image: 'https://robohash.org/consequaturminuset.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
		],
		services: [
			{
				title: 'VP Accounting',
				description: 'Intervertebral disc disorders with myelopathy, lumbar region',
				price: 1500,
				min_time: 10,
			},
			{
				title: 'Structural Analysis Engineer',
				description: 'Injury of other nerves at forearm level, unspecified arm, initial encounter',
				price: 1500,
				min_time: 48,
			},
			{
				title: 'Programmer Analyst I',
				description: 'Assault by sword or dagger, subsequent encounter',
				price: 1500,
				min_time: 29,
			},
			{
				title: 'Assistant Professor',
				description: 'Strain of other muscle(s) and tendon(s) of posterior muscle group at lower leg level, right leg, initial encounter',
				price: 1500,
				min_time: 9,
			},
			{
				title: 'Business Systems Develent Analyst',
				description: 'Multiple perforations of tympanic membrane, left ear',
				price: 1500,
				min_time: 86,
			},
		],
	},
	{
		info: {
			id: 5,
			title: 'Meetz',
			address: '26840 Luster Center',
			contact_phone: '+502 307 422 4682',
			status: 'open',
			work_schedule: 'ПН-СБ',
			time_begin: '8:00',
			time_end: '18:00',
			type: 'SALON',
			images: [
				'http://dummyimage.com/224x100.png/ff4444/ffffff',
				'http://dummyimage.com/245x100.png/dddddd/000000',
				'http://dummyimage.com/223x100.png/5fa2dd/ffffff',
				'http://dummyimage.com/191x100.png/5fa2dd/ffffff',
				'http://dummyimage.com/173x100.png/ff4444/ffffff',
			],
		},
		masters: [
			{
				id: 1,
				gender: 'M',
				name: 'Andrus',
				work_schedule: 'ПН-СБ',
				telegram_id: 'a0',
				surname: 'Parkey',
				image: 'https://robohash.org/maioresfugiatbeatae.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 2,
				gender: 'F',
				name: 'Inessa',
				work_schedule: 'ПН-СБ',
				telegram_id: 'i1',
				surname: 'Narraway',
				image: 'https://robohash.org/possimusprovidentblanditiis.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 3,
				gender: 'F',
				name: 'Sammy',
				work_schedule: 'ПН-СБ',
				telegram_id: 's2',
				surname: 'Hullbrook',
				image: 'https://robohash.org/nostrumineum.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 4,
				gender: 'F',
				name: 'Ashly',
				work_schedule: 'ПН-СБ',
				telegram_id: 'a3',
				surname: 'Braunston',
				image: 'https://robohash.org/quorerumdolore.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
			{
				id: 5,
				gender: 'M',
				name: 'Jule',
				work_schedule: 'ПН-СБ',
				telegram_id: 'j4',
				surname: 'Dooly',
				image: 'https://robohash.org/atqueeiusmollitia.png?size=150x150&set=set1',
				time_begin: '8:00',
				time_end: '18:00',
			},
		],
		services: [
			{
				title: 'Cost Accountant',
				description: 'Displaced fracture of proximal phalanx of right lesser toe(s), subsequent encounter for fracture with malunion',
				price: 1500,
				min_time: 87,
			},
			{
				title: 'Technical Writer',
				description: 'Displaced spiral fracture of shaft of ulna, unspecified arm, subsequent encounter for closed fracture with routine healing',
				price: 1500,
				min_time: 46,
			},
			{
				title: 'Legal Assistant',
				description: 'Injury of unspecified nerve at forearm level, left arm, subsequent encounter',
				price: 1500,
				min_time: 91,
			},
			{
				title: 'Accountant II',
				description: 'Nondisplaced transverse fracture of shaft of right fibula, subsequent encounter for closed fracture with delayed healing',
				price: 1500,
				min_time: 21,
			},
			{
				title: 'Nurse Practicioner',
				description: 'Diverticulitis of intestine, part unspecified, with perforation and abscess without bleeding',
				price: 1500,
				min_time: 41,
			},
		],
	},
];

export default salonsData;